version: "3.8"

services:
  auth-db:
    image: mongo:4.4
    container_name: auth-db
    ports:
      - "27018:27017" 
    networks:
      - e-commerce-net

  auth-service:
    build:
      context: ./services/auth-service
      target: development
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://auth-db:27017/auth_db
      - JWT_SECRET=efrei_super_pass
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    depends_on:
      - auth-db
    networks:
      - e-commerce-net

  product-db:
    image: mongo:4.4
    container_name: product-db
    ports:
      - "27019:27017"
    networks:
      - e-commerce-net

  product-service:
    build:
      context: ./services/product-service
      target: development
    container_name: product-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://product-db:27017/product_db
    volumes:
      - ./services/product-service:/app
      - /app/node_modules
    depends_on:
      - product-db
    networks:
      - e-commerce-net

  order-db:
    image: mongo:4.4
    container_name: order-db
    ports:
      - "27020:27017"
    networks:
      - e-commerce-net

  order-service:
    build:
      context: ./services/order-service
      target: development
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://order-db:27017/order_db
    volumes:
      - ./services/order-service:/app
      - /app/node_modules
    depends_on:
      - order-db
    networks:
      - e-commerce-net

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: frontend-dev
    ports:
      - "8080:8080"
    environment:
      - VITE_AUTH_SERVICE_URL=http://auth-service:3001
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3000
      - VITE_ORDER_SERVICE_URL=http://order-service:3002
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - product-service
      - order-service
    networks:
      - e-commerce-net

networks:
  e-commerce-net:
    driver: bridge
